// Generated by gencpp from file demo/Pos.msg
// DO NOT EDIT!


#ifndef DEMO_MESSAGE_POS_H
#define DEMO_MESSAGE_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo
{
template <class ContainerAllocator>
struct Pos_
{
  typedef Pos_<ContainerAllocator> Type;

  Pos_()
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , velocity_x(0.0)
    , velocity_y(0.0)
    , velocity_z(0.0)  {
    }
  Pos_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , velocity_x(0.0)
    , velocity_y(0.0)
    , velocity_z(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef float _velocity_x_type;
  _velocity_x_type velocity_x;

   typedef float _velocity_y_type;
  _velocity_y_type velocity_y;

   typedef float _velocity_z_type;
  _velocity_z_type velocity_z;





  typedef boost::shared_ptr< ::demo::Pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo::Pos_<ContainerAllocator> const> ConstPtr;

}; // struct Pos_

typedef ::demo::Pos_<std::allocator<void> > Pos;

typedef boost::shared_ptr< ::demo::Pos > PosPtr;
typedef boost::shared_ptr< ::demo::Pos const> PosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo::Pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo::Pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'demo': ['/home/xunshuidezhu/ros/src/demo/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo::Pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo::Pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo::Pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo::Pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo::Pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo::Pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo::Pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf196bbe12249df8a028442f21aa04a9";
  }

  static const char* value(const ::demo::Pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf196bbe12249df8ULL;
  static const uint64_t static_value2 = 0xa028442f21aa04a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo::Pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo/Pos";
  }

  static const char* value(const ::demo::Pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo::Pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#经纬高\n\
float64 latitude\n\
float64 longitude\n\
float64 altitude\n\
#适量速度\n\
float32 velocity_x\n\
float32 velocity_y\n\
float32 velocity_z\n\
";
  }

  static const char* value(const ::demo::Pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo::Pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.velocity_x);
      stream.next(m.velocity_y);
      stream.next(m.velocity_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo::Pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo::Pos_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "velocity_x: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_x);
    s << indent << "velocity_y: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_y);
    s << indent << "velocity_z: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_MESSAGE_POS_H
